### ISSUE TITLE
repository name should end with .jl

### ISSUE THREAD

**Issue by stevengj** [sloisel/SparseSparse#1]
By convention, repository names on github for Julia packages should end with `.jl`, i.e. SparseSparse.jl

**Comment by sloisel** [comment]
I agree all the packages I see on github end in `.jl`, I had a lot of trouble creating my packages so I religiously followed the instructions here:

https://pkgdocs.julialang.org/v1/creating-packages/

https://github.com/JuliaCI/PkgTemplates.jl

Following these instructions results in directories that do not have the `.jl` extension.

Perhaps you should file this issue upstream with whatever Julia authority?
