### ISSUE TITLE
type piracy

### ISSUE THREAD

**Issue by stevengj** [sloisel/SparseSparse#2]
Note that methods like `Base.inv(A::SparseMatrixCSC) = A\spdiagm(0=>ones(size(A,1)))` are [type piracy](https://docs.julialang.org/en/v1/manual/style-guide/#Avoid-type-piracy) and make the package harder to compose with other Julia packages.

Just give the function a different name, e.g. `sparseinv`.

**Comment by stevengj** [comment]
(Probably it's better to give it a different name anyway — people shouldn't use this function by accident, since for generic sparse matrices it is likely to give a dense inverse and hence be very inefficient.)

**Comment by sloisel** [comment]
Thanks for your suggestions. I know about type piracy, I'll try to think about what I can do. Note that it is important for my purpose that things should be easily composable. In the example that I provide, the Woodbury matrices have an invert, and it is done by computing inv(A). It may be that A is a BlockDiagonal matrix, or that A is a dense matrix, or that A is a sparse matrix, or some other type of linear operator. So if one does as you suggest, the inverse of a Woodbury matrix becomes a lot more complicated.
