### ISSUE TITLE
No dimension check on operations

### ISSUE THREAD

**Issue by mipals** [sloisel/SparseSparse#3]
I encountered a small issue when using this otherwise phenomenal package. My issue was that the package does not directly check dimensions, meaning that if padding in the form of zeros is added then the computations still run.

A small MWE: Say that `H` is a sparse matrix and `x` is a right-hand side, then
```julia
H\x						# Default SparseArrays.jl solve
H\[x;spzeros(100)]		# SparseSparse.jl solve as RHS is now sparse. This returns same as H\x due to not not checking dimensions
H\[x;sprand(100,0.1)]   # SparseSparse.jl fails the padding is not zeros 
```

I do not know if it is intended or not, but it took me a while to realize that something was wrong with the dimensions in my code as the SparseSparse solve was not failing.

**Comment by sloisel** [comment]
Sorry I just saw this issue you posted. I've pushed what I believe to be a fix.

**Comment by mipals** [comment]
Hey! No worries, the issues was just meant as a heads up 😃
